development:
  adapter: postgresql
  encoding: SQL_ASCII
  database: project_development
  pool: 5
  username: postgres
  password: postgres

test: &TEST
  adapter: postgresql
  encoding: SQL_ASCII
  database: project_test
  pool: 5
  username: postgres
  password: postgres

production:
  host: ec2-23-23-81-189.compute-1.amazonaws.com
  adapter: postgresql
  encoding: utf8
  database: d6g1ch10mvcg87
  username: pighezbiktbohn
  password: L6_DpO18Ew5OUPI6Ohih0-XWo0